[package]
name = "spc-presenter-rs"
version = "0.1.1"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
spc = { path = "external/spc" }
raqote = { version = "0.8", default-features = false }
image = "0.24"
ringbuf = "0.3.3"
ffmpeg-next = "6.1"
ffmpeg-sys-next = "6.1"
clap = "4.3.1"
encoding_rs = "0.8.32"
indicatif = "0.17.5"
pitch-detection = { path = "external/pitch_detection" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
csscolorparser = "0.6.2"
slint = "1.1.1"
native-dialog = "0.6.3"
rand = "0.8.5"

[build-dependencies]
slint-build = "1.1.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
